### ISSUE TITLE
Project naming

### ISSUE THREAD

**Issue by variablestudio** [variablestudio/var-docs#1]
Proposed scheme VARYYNNN-client-project e.g.:

VAR14012-nike-fibers

**Comment by variablestudio** [comment]
Problems:

**Project pre UK**
City Icon is on Variable website but it’s done by Variable v/ Marcin Ignac in Denmark not LTD in UK so it’ls like VAR13-001 (-1)

**Invoicing for long term projects**
If I do VAR14070-hbd-disco-disco and invoice then invoices are VAR14070/1, VAR14070/2 `wrong!` it was invoiced in 2015 and stuff we are doing now it’s like  VAR14070/3 but invoice should be  VAR15072/1 so i would need to decouple invoices numbering from project numbering = mess

**Comment by vorg** [comment]
Problems:

Project pre UK
City Icon is on Variable website but it’s done by Variable v/ Marcin Ignac in Denmark not LTD in UK so it’ls like VAR13-001 (-1)

Invoicing for long term projects
If I do VAR14070-hbd-disco-disco and invoice then invoices are VAR14070/1, VAR14070/2 wrong! it was invoiced in 2015 and stuff we are doing now it’s like VAR14070/3 but invoice should be VAR15072/1 so i would need to decouple invoices numbering from project numbering = mess

**Comment by automat** [comment]
**2.** 
Then i guess the only option would be to make year a parameter as well, so that projects are mainly sorted by global counter. `VAR070-15-company-bla` & invoices  `VAR070/14/01` with subproject in following year  `VAR070/15/01`.
